part1:
	gcc -std=c99 -g -o part1 part1.c 
part2:
	gcc -std=c99 -g -o part2 part2.c 
part3:
	gcc -std=c99 -g -o part3 part3.c 
part4:
	gcc -std=c99 -g -o part4 part4.c 
clean1:
	rm -f core *.o part1
clean2:
	rm -f core *.o part2
clean3:
	rm -f core *.o part3
clean4:
	rm -f core *.o part4